name: tsh
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+70

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #format time
  intl: ^0.16.0
  #clock
  slide_digital_clock: ^1.0.0
  timer_builder: ^1.3.0
  #svg
  flutter_svg: ^0.22.0
  #dropdown
  dropdown_below: ^0.0.6
  #service locator
  get_it: ^5.0.6
  #bloc
  flutter_bloc: ^6.1.3
  equatable: ^1.2.6
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker:
    path: packages/data_connection_checker-0.3.4
  http: ^0.12.0+3
  # Local cache
  shared_preferences: ^0.5.6
  #deep link
  uni_links: ^0.2.0
  #agora
  agora_rtc_engine: ^4.0.6
  #permission
  permission_handler: ^8.1.4+2
  #permission
  flutter_appauth:
  #Loading
  skeleton_animation: ^0.1.3
  flutter_spinkit: "^4.1.2"
  flutter_easyloading: ^2.2.2
  #dialog
  awesome_dialog: ^1.3.2
  #responsive
  responsive_builder: ^0.3.0
  #toggle switch
  group_button: ^1.3.0
  #mutex
  mutex: ^1.1.0
  #socket client
  socket_io_client:
    path: packages/socket_io_client-0.9.12
  #compare array
  collection: ^1.14.13
  #appsflyer
  appsflyer_sdk: ^6.2.3+1

  #icon
  font_awesome_flutter: ^8.12.0

  #tap_debouncer
  tap_debouncer: ^1.0.1

  #JSON
  json_serializable:
  #font
  google_fonts: ^1.1.2
  #open setting
  # system_settings: ^1.0.1
  open_settings: ^2.0.2

  snack: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/montserrat/Montserrat-Bold.ttf
  #       - asset: fonts/montserrat/Montserrat-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
